<?php

namespace App\Console\Commands;

use App\Models\Company;
use App\Models\Event;
use Illuminate\Console\Command;

class GenerateEvent extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'generate:event';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate a new event entry in the events table';

    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        // Step 1: Input nama event
        $eventName = $this->ask('Event apa yang akan dibuat (nama event)?');

        // Step 2: Pilihan tipe event
        $eventType = $this->choice(
            'Apa tipe dari event tersebut?',
            ['AP', 'Group', 'National', 'International'],
            0
        );

        // Step 3: Pilih company
        $companies = Company::all();
        $companyOptions = $companies->pluck('company_name', 'company_code')->toArray();
        $companyCode = $this->choice(
            'Pilih company untuk event ini:',
            $companyOptions
        );

        // Masukkan data ke database
        Event::create([
            'event_name' => $eventName,
            'company_code' => $companyCode,
            'date_start' => now(),
            'date_end' => now()->addDays(30),
            'status' => 'active',
            'year' => now()->year,
            'description' => 'Generated by command',
            'type' => $eventType,
        ]);

        $this->info("Event '{$eventName}' berhasil dibuat.");
    }
}
