FROM php:8.2.0-fpm

# Instal ekstensi PHP yang diperlukan
RUN apt-get update && apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql \
    && apt-get install -y libzip-dev \
    && docker-php-ext-install zip \
    && docker-php-ext-install pgsql pdo_pgsql \
    && apt-get install -y libcurl4-openssl-dev curl\
    && docker-php-ext-install curl


RUN apt-get install -y unzip

RUN apt-get install -y git

# Instal composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Instal composer sebagai pengguna normal
RUN useradd -ms /bin/bash composeruser
USER composeruser

# Instal Firebase JWT
RUN composer require firebase/php-jwt

# Expose port 9000 (default port PHP-FPM)
EXPOSE 9000